export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const AUTH_NEWREGISTER = 'AUTH_NEWREGISTER';
export const AUTH_NEWREGISTER_SUCCESS = 'AUTH_NEWREGISTER_SUCCESS';
export const AUTH_NEWREGISTER_FAILED =  'AUTH_NEWREGISTER_FAILED';

export const AUTH_FORGOT = 'AUTH_FORGOT';
export const AUTH_FORGOT_SUCCESS = 'AUTH_FORGOT_SUCCESS';
export const AUTH_FORGOT_FAILED =  'AUTH_FORGOT_FAILED';
